---

- name: update repo information
  raw: sudo apt update

- name: Install php
  apt:
    pkg:
      - php{{ php_version }}
      - php-mysql
      - libapache2-mod-php
      - unzip

- name: install php mbstring
  raw: sudo apt install -y php{{ php_version }}-mbstring

- name: Enable mbstring
  raw: sudo phpenmod mbstring

- name: Enable the Apache rewrite module.
  raw: sudo a2enmod rewrite

- name: Install PHP modules for Magento
  raw: sudo apt install -y php{{ php_version }}-bcmath php{{ php_version }}-intl php{{ php_version }}-soap php{{ php_version }}-zip php{{ php_version }}-gd php{{ php_version }}-json php{{ php_version }}-curl php{{ php_version }}-cli php{{ php_version }}-xml php{{ php_version }}-xmlrpc php{{ php_version }}-gmp php{{ php_version }}-common

- name: Restarting Apache(httpd) server
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: Configure php.ini
  ansible.builtin.lineinfile:
    path: /etc/php/{{ php_version }}/cli/php.ini
    regexp: 'max_execution_time=60'
    line: 'max_execution_time=18000'

- name: Configure php.ini
  ansible.builtin.lineinfile:
    path: /etc/php/{{ php_version }}/cli/php.ini
    regexp: 'max_input_time=60'
    line: 'max_input_time=1800'

- name: Configure php.ini
  ansible.builtin.lineinfile:
    path: /etc/php/{{ php_version }}/cli/php.ini
    regexp: 'memory_limit = 128M'
    line: 'memory_limit = 2G'

- name: Restarting Apache(httpd) server
  ansible.builtin.service:
    name: apache2
    state: restarted











# - name: Configure php.ini
#   ansible.builtin.lineinfile:
#     path: /etc/php/7.4/apache2/php.ini
#     regexp: ';opcache.save_comments=1'
#     line: 'opcache.save_comments=1'

# - name: Configure php.ini
#   ansible.builtin.lineinfile:
#     path: /etc/php/7.4/apache2/php.ini
#     regexp: 'realpath_cache_size =*'
#     line: 'realpath_cache_size = 10M'

# - name: Configure php.ini
#   ansible.builtin.lineinfile:
#     path: /etc/php/7.4/apache2/php.ini
#     regexp: 'realpath_cache_ttl = *'
#     line: 'realpath_cache_ttl = 7200'

# - name: Restarting Apache(httpd) server
#   ansible.builtin.service:
#     name: apache2
#     state: restarted

# - name: Enable rewrite module
#   shell: /usr/sbin/a2enmod rewrite

# - name: Enable rewrite module
#   shell: /usr/sbin/a2enmod php7.4

# - name: Restarting Apache(httpd) server
#   ansible.builtin.service:
#     name: apache2
#     state: restarted
