---

- name: update os
  raw: sudo apt-get update

- name: Install apache web server
  apt:
    pkg:
      - apache2

- name: Starting Apache2(httpd) server
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes
  
- name: Create document root
  file:
    path: "/var/www/{{ domain_name }}"
    state: directory
    owner: "ubuntu"
    group: "www-data"
    mode: '0755'

- name: Set up Apache VirtualHost
  template:
    src: ./apache.conf.j2
    dest: /etc/apache2/sites-available/{{ domain_name }}.conf

- name: Restarting Apache2(httpd) server
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: Enable new site
  shell: /usr/sbin/a2ensite {{ domain_name }}.conf
    
- name: Restarting Apache2(httpd) server
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: Disable default Apache site
  shell: /usr/sbin/a2dissite 000-default.conf
      
- name: Restarting Apache2(httpd) server
  ansible.builtin.service:
    name: apache2
    state: restarted
